function goggleViewer(t)
%% Main object definitions
hFig=figure(...
    'Name', sprintf('GoggleBox: %s', t.experimentName), ...
    'NumberTItle', 'off', ...
    'MenuBar', 'none', ...
    'Position', [2561 196 1680 1028], ...
    'ColorMap', gray(256));
hImgAx=axes(...
    'Box', 'on', ...
    'YDir', 'reverse', ...
    'Color', [0 0 0], ...
    'XTick', [], 'YTick', [], ...
    'Position', [0.02 0.02 0.8 0.96]);
%% UI object definitions
%% Backend definitions
currentDSStack=t.downscaledStacks(1); %Default to the first available
currentZIdx=1;
%% Run
hCurrentBaseImage=drawDownscaledBaseImage(hImgAx, currentDSStack, currentZIdx);



end

function hBaseImg=drawDownscaledBaseImage(hAx, TVDSS, idx)
[x, y]=getDSStackCoordinates(TVDSS, idx);
hBaseImg=image('XData', x, 'YData', y, ...
      'CData', TVDSS.I(:,:,idx), 'CDataMapping', 'scaled', ...
      'Parent', hAx);
end

function [x,y,z]=getDSStackCoordinates(TVDSS, idx)
x=1:size(TVDSS.I, 2)*TVDSS.xyds;
y=1:size(TVDSS.I, 1)*TVDSS.xyds;
z=TVDSS.idx(idx);
end