classdef goggleInfoPanel<handle
    properties(SetAccess=protected)
        mainPanel
        goggleViewerDisplay
        xLimMin
        xLimMax
        yLimMin
        yLimMax
        zPosition
    end
    methods
        function obj=goggleInfoPanel(parent, position, gvd)
           
            obj.goggleViewerDisplay=gvd; %associated display object
            obj.goggleViewerDisplay.InfoPanel=obj;
            obj.mainPanel=uipanel(...
                'Parent', parent, ...
                'Units', 'normalized', ...
                'Position', position);
            
            %% Labels
            
            uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.17 0.875 0.4 0.1], ...
                'String', 'View', ...
                'FontSize', 12, ...
                'FontWeight', 'bold', ...
                'HorizontalAlignment', 'center');

            uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.02 0.8 0.2 0.1], ...
                'String', 'X:', ...
                'FontSize', 12, ...
                'FontWeight', 'bold');
             uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.02 0.7 0.2 0.1], ...
                'String', 'Y:', ...
                'FontSize', 12, ...
                'FontWeight', 'bold');
             uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.02 0.5 0.2 0.1], ...
                'String', 'Z:', ...
                'FontSize', 12, ...
                'FontWeight', 'bold');
            
           
           %% Labels which change with data
            obj.xLimMin=uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.17 0.79 0.2 0.1], ...
                'String', '');
            obj.xLimMax=uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.37 0.79 0.2 0.1], ...
                'String', '');
            
             obj.yLimMin=uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.17 0.69 0.2 0.1], ...
                'String', '');
            obj.yLimMax=uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.37 0.69 0.2 0.1], ...
                'String', '');
             obj.zPosition=uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.27 0.49 0.2 0.1], ...
                'String', '');
        end
        function updateDisplay(obj)
            xl=round(xlim(obj.goggleViewerDisplay.axes));
            obj.xLimMin.String=sprintf('%i', xl(1));
            obj.xLimMax.String=sprintf('%i', xl(2));

            
            yl=round(ylim(obj.goggleViewerDisplay.axes));
            obj.yLimMin.String=sprintf('%i',yl(1));
            obj.yLimMax.String=sprintf('%i',yl(2));
            
            z=obj.goggleViewerDisplay.currentZPlaneOriginalCoords;
            obj.zPosition.String=sprintf('%i', z);
        end
    end
end



