classdef goggleInfoPanel<handle
    properties(SetAccess=protected)
        mainPanel
        goggleViewerDisplay
        xLimMin
        xLimMax
        yLimMin
        yLimMax
        zPosition
        viewMode
        downSamplingFactor
    end
    methods
        function obj=goggleInfoPanel(parent, position, gvd)
           
            obj.goggleViewerDisplay=gvd; %associated display object
            obj.goggleViewerDisplay.InfoPanel=obj;
            obj.mainPanel=uipanel(...
                'Parent', parent, ...
                'Units', 'normalized', ...
                'Position', position);
            fontSz=12;
            %% Labels
            
            uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.17 0.875 0.4 0.1], ...
                'String', 'View', ...
                'FontSize', fontSz+2, ...
                'FontWeight', 'bold', ...
                'HorizontalAlignment', 'center');

            uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.02 0.8 0.2 0.1], ...
                'String', 'X:', ...
                'FontSize', fontSz+2, ...
                'FontWeight', 'bold');
             uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.02 0.7 0.2 0.1], ...
                'String', 'Y:', ...
                'FontSize', fontSz+2, ...
                'FontWeight', 'bold');
             uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.02 0.5 0.2 0.1], ...
                'String', 'Z:', ...
                'FontSize', fontSz+2, ...
                'FontWeight', 'bold');
            
            uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.02 0.35 0.47 0.1], ...
                'String', 'View Mode', ...
                'FontSize', fontSz, ...
                'FontWeight', 'bold');
             uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.49 0.35 0.47 0.1], ...
                'String', 'Downsampling', ...
                'FontSize', fontSz, ...
                'FontWeight', 'bold');
           
           %% Labels which change with data
            obj.xLimMin=uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.17 0.8 0.2 0.1], ...
                'String', '', ...
                'FontSize', fontSz);
            obj.xLimMax=uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.37 0.8 0.2 0.1], ...
                'String', '', ...
                'FontSize', fontSz);
            
             obj.yLimMin=uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.17 0.7 0.2 0.1], ...
                'String', '', ...
                'FontSize', fontSz);
            obj.yLimMax=uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.37 0.7 0.2 0.1], ...
                'String', '', ...
                'FontSize', fontSz);
             obj.zPosition=uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.17 0.5 0.66 0.1], ...
                'String', '', ...
                'FontSize', fontSz, ...
                'HorizontalAlignment', 'center');
            
             obj.viewMode=uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.02 0.28 0.47 0.1], ...
                'String', '', ...
                'FontSize', fontSz, ...
                'HorizontalAlignment', 'center');
             obj.downSamplingFactor=uicontrol(...
                'Style', 'text', ...
                'Parent', obj.mainPanel, ...
                'Units', 'normalized', ...
                'Position', [0.49 0.28 0.47 0.1], ...
                'String', '', ...
                'FontSize', fontSz, ...
                'HorizontalAlignment', 'center');
        end
        function updateDisplay(obj)
            xl=round(xlim(obj.goggleViewerDisplay.axes));
            obj.xLimMin.String=sprintf('%i', xl(1));
            obj.xLimMax.String=sprintf('%i', xl(2));

            
            yl=round(ylim(obj.goggleViewerDisplay.axes));
            obj.yLimMin.String=sprintf('%i',yl(1));
            obj.yLimMax.String=sprintf('%i',yl(2));
            
            zIdx=obj.goggleViewerDisplay.currentIndex;
            zIdxOrignalLayerID=obj.goggleViewerDisplay.currentZPlaneOriginalLayerID;
            
            zActual=obj.goggleViewerDisplay.tvdss.zCoords(zIdx);
            obj.zPosition.String=sprintf('Layer %04i (%ium)', zIdxOrignalLayerID, round(zActual));
            %% Zoom indicator
            zoomLevel=obj.goggleViewerDisplay.zoomLevel;
            dsFactor=obj.goggleViewerDisplay.downSamplingForCurrentZoomLevel;
            stackDsFactor=obj.goggleViewerDisplay.tvdss.xyds;
            
            if zoomLevel<=obj.goggleViewerDisplay.minZoomLevelForDetailedLoad
                obj.viewMode.String='Overview';
                obj.downSamplingFactor.String=sprintf('%ux',stackDsFactor);
            elseif dsFactor>1
                obj.viewMode.String='Detail';
                obj.downSamplingFactor.String=sprintf('%ux', dsFactor);
            elseif dsFactor==1
                obj.viewMode.String='Detail';
                obj.downSamplingFactor.String='None';
            else
                error('Unrecognised downSampling/zoomLevels')
            end
               
        end
    end
end



