function selectedDSS = selectDownscaledStack(dss)
%SELECTDOWNSCALEDSTACK Displays information about downscaled stacks to the
%user, in order to get them to choose one!

%#ok<*AGROW>

fontSz=12;
mainFont='Titillium';

if ~isa(dss, 'TVDownscaledStack')
    error('Input must be an array of TVDownscaledStack')
end

if numel(dss)==1
    selectedDSS=dss;
else
    hFig=dialog(...
        'Name', sprintf('Select pregenerated overview stack for %s',dss(1).experimentName), ...
        'ButtonDownFcn', '');
    
    availableChannels=unique({dss.channel});
    hStackInfoBox=uicontrol(...
        'Parent', hFig, ...
        'Units', 'normalized', ...
        'Position', [0.24 0.12 0.74 0.86], ...
        'FontName', mainFont, ...
        'FontSize', fontSz, ...
        'Style', 'listbox', ...
        'String', '', ...
        'Callback', @selectedStackChanged);
    hChannels=uicontrol(...
        'Parent', hFig, ...
        'Units', 'normalized', ...
        'Position', [0.02 0.12 0.2 0.86], ...
        'FontName', mainFont, ...
        'FontSize', fontSz, ...
        'Style', 'listbox', ...
        'String', availableChannels, ...
        'Callback', @selectedChannelChanged);
    hOKButton=uicontrol(...
        'Parent', hFig, ...
        'Units', 'normalized', ...
        'Position', [0.8 0.02 0.18 0.08], ...
        'FontName', mainFont, ...
        'FontSize', fontSz, ...
        'Style', 'pushbutton', ...
        'String', 'OK', ...
        'Callback', 'uiresume(gcbf)'); %#ok<NASGU>
    hOKButton=uicontrol(...
        'Parent', hFig, ...
        'Units', 'normalized', ...
        'Position', [0.6 0.02 0.18 0.08], ...
        'FontName', mainFont, ...
        'FontSize', fontSz, ...
        'Style', 'pushbutton', ...
        'String', 'Cancel', ...
        'Callback', @cancelButtonClick); %#ok<NASGU>
    
    selectedChannelChanged();
    selectedIdx=[];
    selectedStackChanged();
    uiwait(hFig);
    %% We're done, what have we selected?
    if ~isempty(selectedIdx)
        selectedDSS=dss(selectedIdx);
    else
        selectedDSS=[];
    end
    close(hFig)
end

    function selectedChannelChanged(~,~)
        stacksWithMatchingChannelIdx=find(strcmp({dss.channel}, hChannels.String(hChannels.Value)));
        hStackInfoBox.Value=1;
        hStackInfoBox.String='';
        for ii=stacksWithMatchingChannelIdx
            idx=dss(ii).idx-1;
            step=unique(diff(idx));
            if numel(step)==1
                if step==1
                    thisStackDisplayString=sprintf('Slices %u-%u, every slice', idx(1), idx(end));
                else
                    thisStackDisplayString=sprintf('Slices %u-%u, every %u slices', idx(1), idx(end), step);
                end
            else
                thisStackDisplayString=sprintf('Unevenly sampled stack from slice %u to %u', idx(1), idx(end));
            end
            if dss(ii).xyds==1
                thisStackDisplayString=[thisStackDisplayString '. No downsampling'];
            else
                thisStackDisplayString=sprintf('%s. Downsampled %ux in XY', thisStackDisplayString, dss(ii).xyds);
            end
            hStackInfoBox.String{end+1}=thisStackDisplayString;
        end
    end

    function selectedStackChanged(~,~)
        stacksWithMatchingChannelIdx=find(strcmp({dss.channel}, hChannels.String(hChannels.Value)));
        selectedIdx=stacksWithMatchingChannelIdx(hStackInfoBox.Value);
    end
    function cancelButtonClick(~,~)
        selectedIdx=[];
        uiresume(gcbf)
    end

   
end
