function selectedDSS = selectDownscaledStack(mosaicInfo)
%SELECTDOWNSCALEDSTACK Displays information about downscaled stacks to the
%user, in order to get them to choose one!

%#ok<*AGROW>

fontSz=12;
mainFont='Titillium';
%%

if ~isa(mosaicInfo, 'TVStitchedMosaicInfo')
    error('Input must a TVStitchedMosaicInfo object')
end

dss=mosaicInfo.downscaledStacks;

if numel(dss)==1
    selectedDSS=dss;
else
    %% UI Declarations
    hFig=dialog(...
        'Name', sprintf('Select pregenerated overview stack for %s',dss(1).experimentName), ...
        'ButtonDownFcn', '');
    % Ensure it's wide enough
    pos=hFig.Position;
    if pos(3)<800
        pos(3)=800;
        hFig.Position=pos;
    end
    
    availableChannels=unique({dss.channel});
    hStackInfoBox=uicontrol(...
        'Parent', hFig, ...
        'Units', 'normalized', ...
        'Position', [0.24 0.12 0.74 0.86], ...
        'FontName', mainFont, ...
        'FontSize', fontSz, ...
        'Style', 'listbox', ...
        'String', '', ...
        'Callback', @selectedStackChanged);
    hChannels=uicontrol(...
        'Parent', hFig, ...
        'Units', 'normalized', ...
        'Position', [0.02 0.12 0.2 0.86], ...
        'FontName', mainFont, ...
        'FontSize', fontSz, ...
        'Style', 'listbox', ...
        'String', availableChannels, ...
        'Callback', @selectedChannelChanged);
    hOKButton=uicontrol(...
        'Parent', hFig, ...
        'Units', 'normalized', ...
        'Position', [0.8 0.02 0.18 0.08], ...
        'FontName', mainFont, ...
        'FontSize', fontSz, ...
        'Style', 'pushbutton', ...
        'String', 'OK', ...
        'Callback', 'uiresume(gcbf)'); %#ok<NASGU>
    hCancelButton=uicontrol(...
        'Parent', hFig, ...
        'Units', 'normalized', ...
        'Position', [0.6 0.02 0.18 0.08], ...
        'FontName', mainFont, ...
        'FontSize', fontSz, ...
        'Style', 'pushbutton', ...
        'String', 'Cancel', ...
        'Callback', @cancelButtonClick); %#ok<NASGU>
    hNewButton=uicontrol(...
        'Parent', hFig, ...
        'Units', 'normalized', ...
        'Position', [0.02 0.02 0.18 0.08], ...
        'FontName', mainFont, ...
        'FontSize', fontSz, ...
        'Style', 'pushbutton', ...
        'String', 'New', ...
        'Callback', @newButtonClick);%#ok<NASGU>
    hDeleteButton=uicontrol(...
        'Parent', hFig, ...
        'Units', 'normalized', ...
        'Position', [0.22 0.02 0.18 0.08], ...
        'FontName', mainFont, ...
        'FontSize', fontSz, ...
        'Style', 'pushbutton', ...
        'String', 'Delete');%#ok<NASGU>
    %% Main
    selectedChannelChanged();
    selectedIdx=[];
    selectedStackChanged();
    uiwait(hFig);
    %% We're done, what have we selected?
    if ~isempty(selectedIdx)
        selectedDSS=dss(selectedIdx);
    else
        selectedDSS=[];
    end
    close(hFig)
end

    function selectedChannelChanged(~,~)
        stacksWithMatchingChannelIdx=find(strcmp({dss.channel}, hChannels.String(hChannels.Value)));
        hStackInfoBox.Value=1;
        hStackInfoBox.String='';
        for ii=stacksWithMatchingChannelIdx
            idx=dss(ii).idx;
            step=unique(diff(idx));
            if numel(step)==1
                if step==1
                    thisStackDisplayString=sprintf('Slices %u-%u (Layers %u-%u), every slice', idx(1), idx(end), idx(1)-1, idx(end)-1);
                else
                    thisStackDisplayString=sprintf('Slices %u-%u (Layers %u-%u), every %u slices', idx(1), idx(end), idx(1)-1, idx(end)-1, step);
                end
            else
                thisStackDisplayString=sprintf('Unevenly sampled stack from slice %u to %u (layers % to %u)', idx(1), idx(end), idx(1)-1, idx(end)-1);
            end
            if dss(ii).xyds==1
                thisStackDisplayString=[thisStackDisplayString '. No downsampling'];
            else
                thisStackDisplayString=sprintf('%s. Downsampled %ux in XY', thisStackDisplayString, dss(ii).xyds);
            end
            hStackInfoBox.String{end+1}=thisStackDisplayString;
        end
    end

    function selectedStackChanged(~,~)
        stacksWithMatchingChannelIdx=find(strcmp({dss.channel}, hChannels.String(hChannels.Value)));
        selectedIdx=stacksWithMatchingChannelIdx(hStackInfoBox.Value);
    end
    function cancelButtonClick(~,~)
        selectedIdx=[];
        uiresume(gcbf)
    end

    function newButtonClick(~, ~)
        a=TVDownscaledStack(mosaicInfo);
        a.generateStack;
        a.writeStackToDisk;
        dss=mosaicInfo.downscaledStacks;
        hChannels.Value=1;       
        selectedChannelChanged();
    end

   
end
